import React from 'react'
import BlockRenderer from '../blocks/BlockRenderer';
import Head from 'next/head';
import styles from './HomePage.module.css'
import { NextPage } from 'next'
import { HomePageData } from '../../models/pages';

interface Props {
    pageData? : HomePageData;
    data: string;
    userAgent: string;
}

const HomePage: NextPage<Props> = ({ pageData, data, userAgent}) => (
    <>
        <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <h1 data-epi-edit="name">
                s
            </h1>
            <div>
                Content Area Data:sss
                {pageData.mainContentArea?.map(({ contentLink }, k) => (
                    <BlockRenderer blockData={contentLink.expanded} key={k} />
                ))}
            </div>
            <div>
                Cloudflare Data {data}
            </div>
        </main>

        <footer className={styles.footer}>
        </footer>
        </div>
    </>
)

HomePage.getInitialProps = async ({ req }) => {
    const res = await fetch('https://blue-dawn-a640.jonjones.workers.dev/')
    const data = await res.text()
    return {data: data, userAgent: "kk" }
}

export default HomePage;