import Head from 'next/head'
import styles from '../styles/Home.module.css'

function Home(props) {
  const { data } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {data}
        </h1>

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

Home.getInitialProps = async (ctx) => {
  const res = await fetch('https://blue-dawn-a640.jonjones.workers.dev/')
  const data = await res.text()
  return {data}
}

export default Home